graph TD
  FailedRound
  FinishedRound
  StakingContractIntegrationFailedRound
  FailedRound
  InitializationRound
  AgentSetupRound
  StakingContractIntegrationRound
  AgentSetupTimeoutRound
  AgentSetupFailedRound
  StakingContractIntegrationTimeoutRound
  ResetRound
  InitializationRound -->|DONE| AgentSetupRound
  InitializationRound -->|MAX_RETRIES| FailedRound
  AgentSetupRound -->|DONE| StakingContractIntegrationRound
  AgentSetupRound -->|ERROR| AgentSetupFailedRound
  AgentSetupRound -->|TIMEOUT| AgentSetupTimeoutRound
  StakingContractIntegrationRound -->|DONE| FinishedRound
  StakingContractIntegrationRound -->|ERROR| StakingContractIntegrationFailedRound
  StakingContractIntegrationRound -->|TIMEOUT| StakingContractIntegrationTimeoutRound
  AgentSetupFailedRound -->|RETRY| AgentSetupRound
  AgentSetupFailedRound -->|MAX_RETRIES| FailedRound
  AgentSetupTimeoutRound -->|RETRY| AgentSetupRound
  AgentSetupTimeoutRound -->|MAX_RETRIES| FailedRound
  StakingContractIntegrationFailedRound -->|RETRY| StakingContractIntegrationRound
  StakingContractIntegrationFailedRound -->|MAX_RETRIES| FailedRound
  StakingContractIntegrationTimeoutRound -->|RETRY| StakingContractIntegrationRound
  StakingContractIntegrationTimeoutRound -->|MAX_RETRIES| FailedRound
  FinishedRound -->|RESET| ResetRound
  FailedRound -->|RESET| ResetRound
  ResetRound -->|DONE| InitializationRound
  ResetRound -->|ERROR| FailedRound
  ResetRound -->|TIMEOUT| FailedRound
  ResetRound -->|MAX_RETRIES| FailedRound