graph TD
  InitializationRound
  AlternativeFlowRound
  ApplicationCompletionRound
  TimeoutRound
  TokenDistributionRound
  HTSRegistrationRound
  InitializationRound
  ConfirmationRound
  ValidationRound
  ResolutionConfirmationRound
  DisputeResolutionRound
  ErrorHandlingRound
  InitializationRound -->|DONE| DisputeResolutionRound
  DisputeResolutionRound -->|DONE| ResolutionConfirmationRound
  DisputeResolutionRound -->|ERROR| ErrorHandlingRound
  DisputeResolutionRound -->|TIMEOUT| TimeoutRound
  ErrorHandlingRound -->|DONE| DisputeResolutionRound
  TimeoutRound -->|DONE| DisputeResolutionRound
  ResolutionConfirmationRound -->|DONE| HTSRegistrationRound
  HTSRegistrationRound -->|DONE| ValidationRound
  ValidationRound -->|DONE| TokenDistributionRound
  ValidationRound -->|ERROR| ErrorHandlingRound
  TokenDistributionRound -->|DONE| ConfirmationRound
  TokenDistributionRound -->|ERROR| ErrorHandlingRound
  ConfirmationRound -->|DONE| ApplicationCompletionRound
  ErrorHandlingRound -->|RETRY| DisputeResolutionRound
  ErrorHandlingRound -->|ALTERNATE_FLOW| AlternativeFlowRound