graph TD
  ErrorHandlingRound
  ChainlinkOracleIntegrationRound
  TimeoutRound
  InitializationRound
  LayerZeroOmnichainMessagingRound
  PythNetworkDataOracleRound
  ErrorHandlingRound
  FinalizationRound
  HTSContractIntegrationRound
  InitializationRound -->|DONE| HTSContractIntegrationRound
  HTSContractIntegrationRound -->|DONE| ChainlinkOracleIntegrationRound
  ChainlinkOracleIntegrationRound -->|DONE| LayerZeroOmnichainMessagingRound
  LayerZeroOmnichainMessagingRound -->|DONE| PythNetworkDataOracleRound
  PythNetworkDataOracleRound -->|DONE| FinalizationRound
  InitializationRound -->|ERROR| ErrorHandlingRound
  HTSContractIntegrationRound -->|ERROR| ErrorHandlingRound
  ChainlinkOracleIntegrationRound -->|ERROR| ErrorHandlingRound
  LayerZeroOmnichainMessagingRound -->|ERROR| ErrorHandlingRound
  PythNetworkDataOracleRound -->|ERROR| ErrorHandlingRound
  ErrorHandlingRound -->|DONE| InitializationRound
  InitializationRound -->|TIMEOUT| TimeoutRound
  HTSContractIntegrationRound -->|TIMEOUT| TimeoutRound
  ChainlinkOracleIntegrationRound -->|TIMEOUT| TimeoutRound
  LayerZeroOmnichainMessagingRound -->|TIMEOUT| TimeoutRound
  PythNetworkDataOracleRound -->|TIMEOUT| TimeoutRound
  TimeoutRound -->|DONE| InitializationRound